# Generated by Django 5.2 on 2025-04-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefulhabit',
            name='duration',
            field=models.IntegerField(help_text='Укажите продолжительность в секундах', verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='usefulhabit',
            name='periodicity',
            field=models.IntegerField(default=1, help_text='Укажите периодичность выполнения в днях', verbose_name='Периодичность'),
        ),
    ]
